context:
  version: "2.3.2"

recipe:
  name: libzeem
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/zeem/archive/v${{ version }}.tar.gz
  sha256: e7bdf4dd9d8728de9975d8e89989d31bf5b1ad5beb634c632eeeccda12be4c1b

build:
  number: 0

outputs:
  - package:
      name: libzeem
    build:
      script: build
    requirements:
      build:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - pkg-config
        - if: osx
          then:
            - clang-tools
        - if: win
          then:
            - m2-sed
      host:
        - catch2
        - fast_float
        - howardhinnant_date
        - libmcfp
      run_exports:
        # Patch version update may be breakable
        - ${{ pin_subpackage("libzeem", upper_bound="x.x.x") }}
      ignore_run_exports:
        from_package:
          - catch2
    tests:
      - package_contents:
          include:
            - zeem/*
          lib:
            - zeem
        strict: true

  - package:
      name: zeem
    requirements:
      run:
        - ${{ pin_subpackage("libzeem", upper_bound="x.x.x") }}
      run_exports:
        # Patch version update may be breakable
        - ${{ pin_subpackage("zeem", upper_bound="x.x.x") }}
    tests:
      - script:
          interpreter: brush
          - if: linux
            then:
              - test -d "${PREFIX}/include/zeem"
              - test -f "${PREFIX}/lib/libzeem.so"
          - if: osx
            then:
              - test -d "${PREFIX}/include/zeem"
              - test -f "${PREFIX}/lib/libzeem.dylib"
          - if: win
            then:
              - test -d "${LIBRARY_PREFIX}/include/zeem"
              - test -f "${LIBRARY_PREFIX}/lib/zeem.lib"
        requirements:
          run:
            - brush

about:
  homepage: https://www.hekkelman.net/docs/libzeem/
  repository: https://forge.hekkelman.net/maarten/zeem
  documentation: https://www.hekkelman.net/docs/libzeem/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "A C++ Module Library offering a full XML library with validating parser, DOM tree, XPaths and serialization"
  description: |
    This is a feature complete XML library containing a validating parser as well as a modern C++ API for the data structures.
    It also supports serializing custom data structures.

    The core of this library is a validating XML parser with DTD processing and all.
    On top of this are implemented an API for manipulating XML data in a DOM like fashion and a serialization API.
    As a bonus there’s also an XPath implementation, albeit this is limited to XPath 1.0.

    This XML library was extracted from [libzeep](https://github.com/mhekkel/libzeep) since having a separate and simple XML library is more convenient.
    The API is unfortunately no longer compatible since the goal was to be more standards compliant.
    E.g., zeem::element should now be a complete [Sequence Container](https://en.cppreference.com/w/cpp/named_req/SequenceContainer).

extra:
  recipe-maintainers:
    - eunos-1128
