context:
  version: "2.3.0"

package:
  name: zeem
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/zeem/archive/v${{ version }}.tar.gz
  sha256: 006c7954b48061b86f61cb9988b32013e0c3729ce133cec4068231278b004854

build:
  number: 1
  script:
    interpreter: brush
    file: build.sh

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - brush
    - cmake
    - ninja
    - pkg-config
    - if: osx
      then:
        - clang-tools
    - if: win
      then:
        - m2-sed
  host:
    - catch2
    - fast_float
    - howardhinnant_date
    - libmcfp
  run_exports:
    # Patch version update may be breakable
    - ${{ pin_subpackage("zeem", upper_bound="x.x.x") }}
  ignore_run_exports:
    from_package:
      - catch2

tests:
  - package_contents:
      include:
        - zeem/*
      lib:
        - zeem
    strict: true

about:
  homepage: https://www.hekkelman.net/docs/libzeem/
  repository: https://forge.hekkelman.net/maarten/zeem
  documentation: https://www.hekkelman.net/docs/libzeem/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "A C++ Module Library offering a full XML library with validating parser, DOM tree, XPaths and serialization"
  description: |
    This is a feature complete XML library containing a validating parser as well as a modern C++ API for the data structures.
    It also supports serializing custom data structures.

    The core of this library is a validating XML parser with DTD processing and all.
    On top of this are implemented an API for manipulating XML data in a DOM like fashion and a serialization API.
    As a bonus there’s also an XPath implementation, albeit this is limited to XPath 1.0.

    This XML library was extracted from [libzeep](https://github.com/mhekkel/libzeep) since having a separate and simple XML library is more convenient.
    The API is unfortunately no longer compatible since the goal was to be more standards compliant.
    E.g., zeem::element should now be a complete [Sequence Container](https://en.cppreference.com/w/cpp/named_req/SequenceContainer).

extra:
  recipe-maintainers:
    - eunos-1128
